version: 2.1

orbs: 
  maven: circleci/maven@1.3.0


jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn compile
      - run: mvn test verify
      - run: mvn clean package
      - run:
          name: Compress artifact
          command: zip -r artifact.zip .

      - store_artifacts :
          path: ./artifact.zip
          destination: package.zip
