version: 2.1

orbs: 
  maven: circleci/maven@1.3.0


jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn compile
      - run: mvn test verify
      - attach_workspace:
        at: ./target
